#!/bin/bash

# install laravel
composer create-project --prefer-dist laravel/laravel blog && \
  composer require thiagocordeiro/laravel-translator:dev-master#$TRAVIS_COMMIT -d blog/ && \
  cp -R blog/vendor/thiagocordeiro/laravel-translator/tests/Fixtures/App/Functions blog/app && \
  cp -R blog/vendor/thiagocordeiro/laravel-translator/tests/Fixtures/App/View blog/resources/views && \
  rm -rf blog/resources/lang/en && \
  echo "{}" >> blog/resources/lang/pt-br.json && \
  echo "{}" >> blog/resources/lang/es.json && \
  cp blog/vendor/thiagocordeiro/laravel-translator/tests/integration.php blog/
